title: Merahi Village Blog
description: Welcome to Merahi Village
baseurl: ""
url: "https://merahi-village.github.io"
theme: minima

# Social media links
social_links:
  github: merahi-village

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-sitemap

# Pagination
paginate: 10
paginate_path: "/blog/page:num"

# Collections
collections:
  posts:
    output: true
    permalink: /blog/:slug/
