title: Merahi Village Blog
description: Stories and Updates from Merahi Village
baseurl: "/blog"
url: "https://merahi-village.github.io"
permalink: /:year/:month/:day/:title/

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed

# Collections for posts
collections:
  posts:
    output: true
    permalink: /:collection/:year/:month/:day/:title/
